[workspace]
members = [
    "shared",
    "template",
    "ai",
    "app",
    "archive",
    "asciicast",
    "audit-deps",
    "battery",
    "bluetooth",
    "cdm",
    "cert",
    "clean-cache",
    "color-palette",
    "convert",
    "copy-ctx",
    "cron",
    "dedupe",
    "diff",
    "discord",
    "dns",
    "docker",
    "download",
    "encrypt",
    "file-history",
    "find",
    "font",
    "focus",
    "gen-pass",
    "git-extras",
    "img",
    "kill-heavy",
    "local-s3",
    "manage",
    "mc",
    "media",
    "memo",
    "pdf",
    "port-forward",
    "ports",
    "pr",
    "qr",
    "reader",
    "readme",
    "render-md",
    "search-docs",
    "secret",
    "share",
    "share-session",
    "speedtest",
    "ssh",
    "status",
    "storage",
    "todo",
    "tree-view",
    "webhook",
    "wifi",
]
resolver = "2"
