[plugin]
name = "speedtest"
scope = "proto"
version = "0.1.0"
description = "Internet speed test"
author = "proto-cli"
repository = "https://github.com/proto-cli/plugins/tree/main/speedtest"

[plugin.commands]
speedtest = "bin/speedtest"
