use dialoguer::MultiSelect;
use indicatif::{ProgressBar, ProgressStyle};
use owo_colors::OwoColorize;
use std::io::Write;
use std::process::Command;

struct Theme;
impl Theme {
    const HEADER: owo_colors::Style = owo_colors::Style::new().bold().bright_blue();
    const ACCENT: owo_colors::Style = owo_colors::Style::new().bold().cyan();
    const MUTED: owo_colors::Style = owo_colors::Style::new().dimmed();
    const SUCCESS: owo_colors::Style = owo_colors::Style::new().bright_green();
    const ERROR: owo_colors::Style = owo_colors::Style::new().bright_red();
    const WARN: owo_colors::Style = owo_colors::Style::new().bright_yellow();
}

fn header(text: &str) -> String {
    format!("{} {}", "◆".style(Theme::ACCENT), text.style(Theme::HEADER))
}

fn divider() -> String {
    "─".repeat(40).style(Theme::MUTED).to_string()
}

fn muted(msg: &str) -> String {
    format!("{}", msg.style(Theme::MUTED))
}

fn success(msg: &str) -> String {
    format!("{} {}", "✔".style(Theme::SUCCESS), msg)
}

fn warn(msg: &str) -> String {
    format!("{} {}", "⚠".style(Theme::WARN), msg)
}

fn error(msg: &str) -> String {
    format!("{} {}", "✗".style(Theme::ERROR), msg)
}

struct Spinner {
    pb: ProgressBar,
}

impl Spinner {
    fn new(msg: &str) -> Self {
        let pb = ProgressBar::new_spinner()
            .with_message(msg.to_string())
            .with_style(
                ProgressStyle::with_template("{spinner:.cyan} {msg}")
                    .unwrap()
                    .tick_strings(&["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]),
            );
        pb.enable_steady_tick(std::time::Duration::from_millis(80));
        Self { pb }
    }

    fn done(&self, msg: &str) {
        self.pb.finish_with_message(msg.to_string());
    }

    fn fail(&self, msg: &str) {
        self.pb.finish_with_message(
            format!("{} {}", "✗".style(Theme::ERROR), msg.style(Theme::ERROR)),
        );
    }
}

fn which(binary: &str) -> bool {
    Command::new("which")
        .arg(binary)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn run_command_output(program: &str, args: &[&str]) -> std::io::Result<String> {
    let output = Command::new(program).args(args).output()?;
    Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

fn format_size(bytes: u64) -> String {
    const UNITS: &[&str] = &["B", "KB", "MB", "GB", "TB"];
    if bytes < 1024 {
        return format!("{} B", bytes);
    }
    let mut v = bytes as f64;
    let mut i = 0;
    while v >= 1024.0 && i < UNITS.len() - 1 {
        v /= 1024.0;
        i += 1;
    }
    format!("{:.1} {}", v, UNITS[i])
}

fn main() {
    if !which("git") {
        eprintln!("{} Git required.", error(""));
        return;
    }

    let sp = Spinner::new("Scanning repository...");

    let files = run_command_output("git", &["ls-files"]).unwrap_or_default();
    let candidates: Vec<String> = files
        .lines()
        .filter(|l| !l.is_empty())
        .filter(|l| has_interesting_ext(l))
        .map(|s| s.to_string())
        .collect();

    if candidates.is_empty() {
        sp.fail("No source files found.");
        return;
    }

    sp.done(&format!("Found {} files", candidates.len()));

    println!(
        "\n{} Select files (space to toggle, enter to confirm):\n",
        "◆".style(Theme::ACCENT)
    );

    let defaults_full = vec![false; candidates.len()];
    let items: Vec<String> = candidates
        .iter()
        .enumerate()
        .map(|(i, f)| {
            let size = std::fs::metadata(f).map(|m| m.len()).unwrap_or(0);
            format!(
                "{:>3}  {}  {}",
                (i + 1).to_string().dimmed(),
                f.style(Theme::ACCENT),
                format_size(size).dimmed()
            )
        })
        .collect();

    let selection = MultiSelect::with_theme(&dialoguer::theme::ColorfulTheme::default())
        .with_prompt(&format!("Choose files ({} total)", candidates.len()))
        .items(&items)
        .defaults(&defaults_full)
        .interact()
        .unwrap_or_default();

    if selection.is_empty() {
        println!("{} No files selected.", warn(""));
        return;
    }

    let sp = Spinner::new("Building context...");

    let mut md = String::new();
    md.push_str(&format!("## Repository Context\n"));
    md.push_str(&format!("Generated by Proto CLI\n\n"));

    let repo_name = run_command_output(
        "basename",
        &[
            "-s",
            ".git",
            &run_command_output("git", &["config", "--get", "remote.origin.url"])
                .unwrap_or_default(),
        ],
    )
    .unwrap_or_else(|_| "project".into());
    md.push_str(&format!("**Project:** {}\n", repo_name));
    md.push_str(&format!("**Files:** {}\n\n", selection.len()));

    for idx in &selection {
        let file = &candidates[*idx];
        let ext = file.rsplit('.').next().unwrap_or("");
        let lang = lang_for_ext(ext);

        let content =
            std::fs::read_to_string(file).unwrap_or_else(|_| format!("[binary: {}]", file));
        let truncated = if content.lines().count() > 200 {
            let lines: Vec<&str> = content.lines().take(200).collect();
            format!(
                "{}\n... ({} more lines)",
                lines.join("\n"),
                content.lines().count() - 200
            )
        } else {
            content
        };

        md.push_str(&format!("## {}\n", file));
        md.push_str(&format!("```{}\n{}\n```\n\n", lang, truncated));
    }

    sp.done(&format!("{} lines of context ready", md.lines().count()));

    let size = md.len();
    copy_to_clipboard(&md);

    println!(
        "\n{} {} files bundled ({}).",
        success(""),
        selection.len(),
        format_size(size as u64)
    );
    println!(
        "{} Copied to clipboard — paste into your LLM!",
        "  ".dimmed()
    );
}

fn has_interesting_ext(path: &str) -> bool {
    let exts = &[
        "rs", "py", "js", "ts", "tsx", "jsx", "go", "c", "cpp", "h", "hpp", "java", "kt",
        "swift", "rb", "php", "sh", "bash", "zsh", "fish", "toml", "yaml", "yml", "json", "xml",
        "md", "txt", "cfg", "ini", "css", "scss", "html", "vue", "svelte", "sql", "r", "lua",
        "nix", "dockerfile", "makefile", "cmake", "gradle",
    ];
    if let Some(ext) = path.rsplit('.').next() {
        exts.contains(&ext.to_lowercase().as_str())
    } else {
        false
    }
}

fn lang_for_ext(ext: &str) -> &str {
    match ext.to_lowercase().as_str() {
        "rs" => "rust",
        "py" => "python",
        "js" => "javascript",
        "ts" => "typescript",
        "tsx" => "tsx",
        "jsx" => "jsx",
        "go" => "go",
        "c" => "c",
        "cpp" => "cpp",
        "h" => "c",
        "hpp" => "cpp",
        "java" => "java",
        "kt" => "kotlin",
        "swift" => "swift",
        "rb" => "ruby",
        "php" => "php",
        "sh" => "bash",
        "bash" => "bash",
        "zsh" => "bash",
        "fish" => "fish",
        "toml" => "toml",
        "yaml" => "yaml",
        "yml" => "yaml",
        "json" => "json",
        "xml" => "xml",
        "md" => "markdown",
        "css" => "css",
        "scss" => "scss",
        "html" => "html",
        "vue" => "html",
        "svelte" => "html",
        "sql" => "sql",
        "r" => "r",
        "lua" => "lua",
        "nix" => "nix",
        "dockerfile" => "dockerfile",
        "cmake" => "cmake",
        _ => "",
    }
}

fn copy_to_clipboard(text: &str) {
    for cmd in &["wl-copy", "xclip -selection clipboard", "pbcopy"] {
        let parts: Vec<&str> = cmd.split_whitespace().collect();
        let mut child = Command::new(parts[0])
            .args(&parts[1..])
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn();

        if let Ok(ref mut c) = child {
            if c.stdin.as_mut().unwrap().write_all(text.as_bytes()).is_ok() {
                let _ = c.wait();
                return;
            }
        }
    }
}
